Add: ER図の追加
en-Barry/desktour pull request #3
Opened 2021-02-14 16:35 UTC by en-Barry

## 概要
以下のリンクをREADMEに追加
- [MVPを考慮したER図](https://drive.google.com/file/d/1DXEMqbS_7hjjPsu6FCg9g8Q03sJmMHBi/view?usp=sharing)

### 確認していただきたい点
- [ ] 適切に正規化されたテーブル設計ができているか
- [ ] アソシエーションの設定に過不足がないか
- [ ] 「後々追加したい機能」を実装する上でも、テーブル構成に問題はなさそうか

以下、主なMVP機能と後々追加したい機能です
#### MVPを考慮した機能
- ユーザー登録
  - SNSログイン(Twitter, google)
- 投稿機能
  - 一度の投稿に写真最大5枚
  - 写真ごとにキャプション
  - アイテムのタグづけ
- アイテム登録
  - 登録されていないアイテムを[Amazon Product Advertising API](https://d.hatena.ne.jp/keyword/Product%20Advertising%20API)を使って登録 
- コメント機能
- いいね機能
- ブックマーク機能
- シェア機能

#### 後々追加したい機能（仮
- 動画投稿
- アイテムの総額を自動算出
- マイページにYouTube動画登録
- アイテム名やキーワードでの検索機能
- アドバイスください投稿枠を追加

## 気になる点
Post部分の写真とキャプションを、別のテーブルに切り分けてリレーションした方がいいのかどうか
### 実現したいこと
Facebookのように、写真に対してそれぞれキャプションを付けたい

![スクリーンショット 2021-02-15 1 29 05](https://user-images.githubusercontent.com/69828703/107882539-419dbc80-6f2d-11eb-9585-c08411056844.png)

### 現状
一つのPostに対して``` images ```と```captions```に配列で登録する形

2021-02-15 11:10 UTC, yuji91 requested changes
Post部分の写真とキャプションは、別のテーブルに切り分けてリレーションした方がいいですね！

「複数画像を配列としてカラムで対応する」点には以下の問題があります。
- 画像データ削除時にindexがズレてキャプションとの整合性が合わなくなる。
- 画像登録時のバリデーションを設定できない。
- キャプション情報も配列で格納されているため、キーワード検索が実施できない。

そのため Post に対して複数の画像情報を残す場合は post_images という子テーブルを作成して、画像とキャプションをそれぞれカラムで用意して１つのセットとして登録した方が良いですね。
（その場合はフォームオブジェクトを使って登録フォームを実装する必要があるので、それが難しければ一旦画像は１つだけ登録する形で作っておくのが良いかもしれません。）

この「配列に複数データを登録させる」方法はSQLアンチパターンとして挙げられているので、以下のリンクも確認しておいてください。
https://www.slideshare.net/kamekoopa/ss-26685543

また「Post Item間のアソシエーションに対するカラムの定義が不適切」な気がするのでご確認ください。

現状Post と Item のアソシエーションは 多対多 で記載されています。
そして両方のテーブルに関連レコードのIDが記載されています。 
こちらはアソシエーションが 多対多 であれば関連レコードのIDを削除して、中間テーブルを作成するべきですね。
もし１対多の書き間違えであれば、親テーブルのIDを子テーブルのカラムに持っておけば十分で、 親テーブルの Post で 子テーブルの item_id を持つ必要はないので削除する形になります。 
細かい点ですが Railsでテーブルを作成すると各テーブルのPK（主キー）はデフォルトでidになるので、`user_id`とか`comment_id`などと書いてある部分は`id`で良いかと思います。

2021-02-15 14:03 UTC, en-Barry commented
@yuji91  さん
レビュー、回答ありがとうございます！
「配列に複数データを登録させること」の問題点を理解しました。
ご指摘を踏まえ、以下のように修正しました。

### 変更点
-  **```Post_images```を作成し、```Posts```に関連付け**
  
- **中間テーブル```Item_tags```を作成し、```Posts```と```Items```を関連付け**
  - ご指摘の通り```Posts```と```Items```間は多対多の関係なので、中間テーブルを用意しました
- **中間テーブル```Post_categories```を作成し、```Posts```と```categories```を関連付け**
  - 上記と同じく```Posts```と```categories```間も多対多の関係だったので、```Post_categories```を用意しました。
- **PK部分を```id```に変更**


[修正済みER図](https://drive.google.com/file/d/1DXEMqbS_7hjjPsu6FCg9g8Q03sJmMHBi/view?usp=sharing)

確認をよろしくお願い致します。

2021-02-16 02:40 UTC, yuji91 commented
PostImagesテーブルが`image`で`Items`が`image_url`になっているので、統一した方が良いかと思いました！

またBookmarksにはPostsとItemsとどちらのIDもカラムで用意されていますが「PostにもItemにもそれぞれBookmarkできる」という仕様でしょうか？

2021-02-16 06:05 UTC, en-Barry commented
@yuji91 
ご指摘ありがとうございます！
以下修正点と、質問に対する回答です。

- **```Items```テーブルの```image_url```を```image```に名称変更**
  
- **```Bookmarks```テーブルを```PostBookmarks```と```ItemBookmarks```に切り分け**
  - ご質問の通り「PostにもItemにもそれぞれBookmarkできる」という仕様にしたかったので、分かりやすく二つに分けてみました。

[修正済みER図](https://drive.google.com/file/d/1DXEMqbS_7hjjPsu6FCg9g8Q03sJmMHBi/view?usp=sharing)

確認をお願い致します。

2021-02-16 06:11 UTC, en-Barry commented
@yuji91 
すみません追加で修正です
- **```Users```テーブルの```ProfileImage```を```image```に名称変更
 - 上記コメントの修正部分と同じく名称を統一するため

修正済みER図

2021-02-16 11:22 UTC, yuji91 approved these changes
修正確認しました、ER図LGTMです！

2021-02-16 11:30 UTC, merged